name: Continuous integration
on:
  push:
    branches:
      - v4-dev
  pull_request:
    branches:
      - v4-dev
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - ci:check
          - ci:test
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - run: deno task btr ${{ matrix.task }}
  analyze:
    runs-on: ubuntu-latest
    needs:
      - testing
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript-typescript
    steps:
    - uses: actions/checkout@v3
    - uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        queries: security-and-quality
    - uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - run: deno task btr docker:build

